# syntax=docker/dockerfile:1
# Copyright 2025 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


FROM opensandbox/code-interpreter-base:latest

ARG TARGETARCH


# Install Xvfb and browser dependencies (following browserless approach)
RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb \
    dumb-init \
    fonts-liberation \
    libasound2t64 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Set Playwright browsers path before installation (following browserless approach)
ENV PLAYWRIGHT_BROWSERS_PATH=/usr/local/bin/playwright-browsers \
    PUPPETEER_SKIP_DOWNLOAD=true

# Install Playwright and Chromium
RUN source /opt/opensandbox/code-interpreter-env.sh node 22 && \
    npm install -g playwright && \
    npx playwright install chromium --with-deps


ENV CHROMIUM_PATH=/usr/bin/chromium-browser \
    CHROMIUM_VERSION=stable

CMD ["/bin/bash"]
